name: Deploy to Cloud Run via GitHub Actions

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: shashigcp-454502

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker image to Artifact Registry
        run: |
          docker build -t us-central1-docker.pkg.dev/shashigcp-454502/github-actions/hello-image:latest .
          docker push us-central1-docker.pkg.dev/shashigcp-454502/github-actions/hello-image:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy hello-service \
            --image us-central1-docker.pkg.dev/shashigcp-454502/github-actions/hello-image:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
